apiVersion: batch/v1
kind: Job
metadata:
  name: pi-username
spec:
  template:
    spec:
      containers:
      - name: pi
        image: docker.io/perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsGroup: 3000
          runAsUser: 1000
      restartPolicy: Never
  backoffLimit: 4