bases:
- ../../base

patches:
- replicas_patch.yaml
- securitycontext_patch.yaml
- resources_patch.yaml

nameSuffix: -dev

commonLabels:
  app: aurora-example-flask-app
  argocd.argoproj.io/instance: hello-world-instance

namespace: pare
images:
- name: hello-world
  newName: auroradevacr.azurecr.io/workshop/flask-app-pare
  newTag: "0"
