apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-flask-app
spec:
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
