apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-flask-app
spec:
  template:
    spec:
      containers:
      - name: hello-world
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 3000
          runAsUser: 1000
          runAsNonRoot: true
